# Generated by Django 3.0.6 on 2020-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_type',
            options={'verbose_name': 'Вид работ в заказе', 'verbose_name_plural': 'Виды работ в заказе'},
        ),
        migrations.AlterModelOptions(
            name='type_of_work',
            options={'verbose_name': 'Вид работы', 'verbose_name_plural': 'Виды работ'},
        ),
        migrations.AlterField(
            model_name='order_type',
            name='count',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
