# Generated by Django 3.0.6 on 2020-06-10 10:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер обратной связи'),
        ),
    ]
